### ISSUE TITLE
CodiceFiscale.of(String code) IllegalArgumentException per cognomi con due lettere

### ISSUE THREAD

**Issue by PepeExpress** [kamaladafrica/codice-fiscale#11]
Ho riscontrato questo bug quando si prova a creare un `CodiceFiscale` passando come argomento la stringa del codice fiscale. In particolare quando si passa il codice fiscale di una persona che ha il cognome composto da solo due lettere (es. Carlo Bo).

Esempio:
`CodiceFiscale.of("BOXCRL80A01F205Z");`

Throws:
```
expected BOXCRL80A01F205Z, but found BXOCRL80A01F205U
java.lang.IllegalArgumentException: expected BOXCRL80A01F205Z, but found BXOCRL80A01F205U
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158)
	at it.kamaladafrica.codicefiscale.CodiceFiscale.of(CodiceFiscale.java:145)
	at it.kamaladafrica.codicefiscale.CodiceFiscale.of(CodiceFiscale.java:116)
```

Dati della persona:
Nome: Carlo
Cognome: Bo
Luogo di nascita: Milano
Provincia: MI
Genere: M
Data Nascita: 01/01/1980

Provo a guardare se riesco a risolvere e in caso apro una PR, se sai tu come risolvere in fretta puoi tranquillamente fixare tu 😄

Grazie

**Comment by PepeExpress** [comment]
Grazie per la tempestività 😄
