### ISSUE TITLE
Cannot call isFormatValid

### ISSUE THREAD

**Issue by FrancYescO** [kamaladafrica/codice-fiscale#24]
Provando ad utilizzare la funzione isFormatValid con un codice fiscale valido es SDSSSD98D01F839O

Al primo check ricevo
```
java.lang.ClassNotFoundException: com.google.common.primitives.ImmutableIntArray
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[na:1.8.0_352]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[na:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[na:1.8.0_352]
	at it.kamaladafrica.codicefiscale.internal.Omocode.<clinit>(Omocode.java:16) ~[codice-fiscale-1.4.0.jar:na]
	at it.kamaladafrica.codicefiscale.internal.AbstractPart.<init>(AbstractPart.java:19) ~[codice-fiscale-1.4.0.jar:na]
	at it.kamaladafrica.codicefiscale.internal.ControlPart.<init>(ControlPart.java:12) ~[codice-fiscale-1.4.0.jar:na]
	at it.kamaladafrica.codicefiscale.internal.ControlPart.of(ControlPart.java:31) ~[codice-fiscale-1.4.0.jar:na]
	at it.kamaladafrica.codicefiscale.CodiceFiscale.isFormatValid(CodiceFiscale.java:176) ~[codice-fiscale-1.4.0.jar:na]
```

riprovando
```
java.lang.NoClassDefFoundError: Could not initialize class it.kamaladafrica.codicefiscale.internal.Omocode
	at it.kamaladafrica.codicefiscale.internal.AbstractPart.<init>(AbstractPart.java:19) ~[codice-fiscale-1.4.0.jar:na]
	at it.kamaladafrica.codicefiscale.internal.ControlPart.<init>(ControlPart.java:12) ~[codice-fiscale-1.4.0.jar:na]
	at it.kamaladafrica.codicefiscale.internal.ControlPart.of(ControlPart.java:31) ~[codice-fiscale-1.4.0.jar:na]
	at it.kamaladafrica.codicefiscale.CodiceFiscale.isFormatValid(CodiceFiscale.java:176) ~[codice-fiscale-1.4.0.jar:na]
```

**Comment by kamaladafrica** [comment]
Sembra che non riesca a risolvere la dipendenza.
Verifica che nel classpath ci siano tutte le dipendenze.

Se il classpath è corretto, fornisci più dettagli:
- Quale versione di java utilizzi?
- È un’applicazione standalone, server, mobile o cosa?
- Stai usando maven per la build?

**Comment by FrancYescO** [comment]
- 1.8
- applicazione server springboot
- si

ps. con un codice fiscale NON valido, ricevo correttamente il false

**Comment by kamaladafrica** [comment]
Non riproducibile.
Funziona correttamente sia da test che da un progetto spring-boot 2.7.10, Java 8.
Se riesci a fare un progetto ed isolare il problema, puoi creare una nuova issue.
